### ISSUE TITLE
test_import.test_answer fails with error

### ISSUE THREAD

**Issue by rabernat** [rabernat/pyqg#3]
This is a new test added by Cesar

```
======================================================================
ERROR: test_import.test_answer
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/anaconda/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/rpa/pyqg/pyqg/tests/test_import.py", line 3, in test_answer
    import mkl
ImportError: No module named mkl
```

**Comment by crocha700** [comment]
This is really a simple issue. I mistakenly assumed the user has mkl, which is not necessary to run the model.
